import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { css } from "@emotion/react";

const Home: NextPage = () => {
  return (
    <div css={style}>
      {/* 
      import { css } from "@emotion/css";
      <div className={style}> 
      */}
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      <div>A</div>
      <div>B</div>
    </div>
  );
};

const style = css`
  background: green;
`;

export default Home;
